# Generated by Django 3.2.6 on 2022-02-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('realname', models.CharField(max_length=40)),
            ],
        ),
    ]
